M48
; DRILL file {KiCad (6.0.9)} date Tue 10 Jan 2023 05:42:00 PM CET
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-01-10T17:42:00+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.9)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0906
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.2835
%
G90
G05
T1
X4.875Y-3.175
T2
X4.875Y-4.1593
T0
M30
